# Generated by Django 5.2 on 2025-04-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rating_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
