# Generated by Django 5.2 on 2025-04-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
