# Generated by Django 5.2 on 2025-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
