# Generated by Django 5.2 on 2025-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_spec_1_product_spec_2_product_spec_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
