# Generated by Django 5.2 on 2025-05-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('female_toys', 'Female Toys'), ('male_toys', 'Male Toys'), ('dildos', 'Dildos'), ('vibrators', 'Vibrators'), ('bondage_kits', 'Bondage Kits'), ('anal_toys', 'Anal_toys'), ('adult_games', 'Aduilt Games'), ('lubes', 'Lubes'), ('condoms', 'Condoms')], max_length=20),
        ),
    ]
