# Generated by Django 5.2 on 2025-04-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
