# Generated by Django 5.2 on 2025-04-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_remove_mpesapayment_status_and_more'),
        ('orders', '0005_order_payment_reference_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payment', to='orders.order'),
        ),
    ]
