# Generated by Django 5.2 on 2025-05-02 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0006_mpesapayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number.', regex='^\\+?254\\d{9}$')]),
        ),
    ]
