# Generated by Django 5.2 on 2025-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
