# Generated by Django 5.2 on 2025-04-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('areas', models.TextField(help_text='Comma-separated areas covered')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
