# Generated by Django 5.2 on 2025-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_deliverylocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='areas',
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
