# Generated by Django 5.2 on 2025-05-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_deliverylocation_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.deliverylocation'),
        ),
    ]
