# Generated by Django 5.2 on 2025-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_reference_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
