# Generated by Django 5.2 on 2025-06-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
